version: "3.9"

services:
  database:
    image: postgres
    networks:
      - backend
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=database-library
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    networks:
      - backend
    container_name: library-backend
    restart: always
    ports: 
      - 3333:3333
    environment:
      - POSTGRES_DB=database-library
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=library
      - POSTGRES_HOST=database
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
    driver: local