version: "3.9"

services:
  database:
    image: keinos/sqlite3:latest
    container_name: database_library
    restart: always
    ports:
      - '9000:9000' 
    stdin_open: true
    tty: true
    volumes:
      - db:/data/sqlite
    
  app:
    build: .
    container_name: library-challenge
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  db:
    driver: local