version: "3.9"

services:
  database:
    image: postgres
    container_name: database-library
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=database-library
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: library-backend
    restart: always
    ports: 
      - 3333:3333
    environment:
      - POSTGRES_DB=database-library
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=library
      - POSTGRES_HOST=database
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local